env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - make build

builds:
  - binary: gooferr
    main: ./cmd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }}, {{ .Os }}/{{ .Arch }})" -X "main.versionString={{ .Tag }}"

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
